### ISSUE TITLE
One application

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [AisakaManatsu/ViT_MicroExpression#2]
Hello, the author. I want to apply for a pre-trained model for learning. I hope you can agree.
<img width="589" alt="image" src="https://user-images.githubusercontent.com/72587415/199234920-b5531ab3-0f3b-41f7-9093-9981eb8f1410.png">

**Comment by YUZHIWANG-bug** [comment]
If you can, please contact me: irecalllost@gmail.com

**Comment by AisakaManatsu** [comment]
Hello, thank you for your interest in our project.😊
We have just started this project and there are still many details to be worked out. This "model_23_0.868.pth" model is the original version which has now been removed, but we can send you a model that works better for ViT, called "VisionTransformer_24_0.878.pth".
We will gradually improve the project and complete the documentation in the future and hope that this will be of help to you. :)

**Comment by YUZHIWANG-bug** [comment]
> 

Oh, that's great. If you can, please send me a copy. Thank you very much!

**Comment by YUZHIWANG-bug** [comment]
> Hello, thank you for your interest in our project.😊 We have just started this project and there are still many details to be worked out. This "model_23_0.868.pth" model is the original version which has now been removed, but we can send you a model that works better for ViT, called "VisionTransformer_24_0.878.pth". We will gradually improve the project and complete the documentation in the future and hope that this will be of help to you. :)

Oh, that's great. If you can, please send me a copy. Thank you very much!

**Comment by YUZHIWANG-bug** [comment]
> Hello, thank you for your interest in our project.😊 We have just started this project and there are still many details to be worked out. This "model_23_0.868.pth" model is the original version which has now been removed, but we can send you a model that works better for ViT, called "VisionTransformer_24_0.878.pth". We will gradually improve the project and complete the documentation in the future and hope that this will be of help to you. :)

I'm very glad to receive your reply. If you can, please send me the pre-trained model. Thank you very much! Thank you for the project, which will be very helpful to me！
